version: '3'

services:
    webserver:
        build: ./webserver
        ports:
        - '5101:80'
        depends_on:
        - configserver
    configserver:
        build: ./configserver
        ports:
        - '5102:5102'
        depends_on:
        - mongodb
    mongodb:
        image: mongo
        ports:
        - '27017:27017'